### ISSUE TITLE
Add support for PlantUML server

### ISSUE THREAD

**Issue by FlashyCoderDude** [talsma-ict/umldoclet#428]
This is a feature request, not a problem.

Would like to know if you can pass the generated commands for the diagrams to a PlantUML server (either web server on the net, or self-running server in a local intranet environment)?

This would prevent users from having to install Graphviz ,and can take advantage of all features of PlantUML as new libraries are released.

**Comment by sjoerdtalsma** [comment]
What I remember from PlantUML server (long time ago) is that it used the URL to contain an encoded version of the textual plantuil diagram. Due to maximum URL sizes (officially `2048` characters) this is feasible only for rather small diagrams.

That is the reason this avenue was never investigated (also I don't want to link to the plantuml main site on my generated javadoc).

But to answer your feature request:
- Yes, technically I think it would be doable, however, for large diagrams it might not work due to URL size limits.
- I currently have not much time to spend on this, so I'm not sure how strong the demand is for this.

For now I'm leaning towards leaving this GitHub issue open and see if there are any additional people commenting they want or even need this.
Feel free to comment yourself to try to change my mind though 😉

**Comment by FlashyCoderDude** [comment]
Thank you for responding to my request!  I know that I use the server-version for my own personal stuff (I use VSCode and a web-version [not plantuml.com] to render diagrams).  Unfortunately, I do not know if this is a GET or POST request (I guess I can go look).

If a POST request, the URL issue would not be a problem, and it would alleviate you from needing to embed the plantuml code directly in the doclet code.

It is a little odd that there are not others needing this and I for one really enjoy your work.  Being able to automatically generate Class Diagrams in Javadocs is amazing and so needed.

Thanks again for all your effort.

**Comment by sjoerdtalsma** [comment]
Support was added in `2.1.0`
