### ISSUE TITLE
No connection is drawn for return value types

### ISSUE THREAD

**Issue by hupfdule** [talsma-ict/umldoclet#495]
I don’t know if this is intended or can be considered a bug. Please feel free to close this issue if you think the current behavior is correct.

## Expected Behavior

If class “A” has a method with a return value “B” there is no connection drawn between these classes.

## Actual Behavior

No association is drawn.

## Steps to Reproduce the Problem

Please see this example: https://javadoc.io/doc/de.poiu.coat/coat-runtime/latest/de/poiu/coat/validation/package-summary.html

The `ValidationResult` has a method that returns a `List<ValidationFailure>`, but no association is drawn between these classes. I would expect this to be the case. I have checked that the problem is not that `ValidationFailure` is only a type parameter of `List`. The same is true if it returns a single `ValidationFailure`.

The source code for `ValidationResult` can be found [here](https://github.com/poiu-de/coat/blob/coat-0.0.4/coat-runtime/src/main/java/de/poiu/coat/validation/ValidationResult.java)

## Specifications

  - Version: 2.1.0
  - Platform: Linux
  - Java version: 11
  - (If open source) Project link: https://poiu-de.github.io/coat/  /  https://github.com/poiu-de/coat

**Comment by sjoerdtalsma** [comment]
What _kind_ of class association would you expect here?
We intentionally don't render _uses_ relations (only _extends_, _implements_ and _inner class_) by default because that usually leads to very crowded diagrams.

If you do require _uses_ relations to be added, please reopen this issue, with a motivation where this is useful and whether 'external' uses relations (such as `java.lang.String`?) should also be added?
The return types, parameters and class fields _are_ considered when determining package dependencies.

**Comment by hupfdule** [comment]
I would expect a _uses_ relation. That is the only one that makes sense here. But I also understand that by drawing every _uses_ association the diagrams could get crowded. 
It could be nice if they could be supported somehow (e.g. by explicitly declaring when to draw these _usage_ associations), but I don’t know whether it would be worthwhile and also don’t know how this could be specified. Therefore I am fine with your decision to just close this issue.
